config/routes.rb
Rails.application.routes.draw do


  resources :email_settings
  get '/donations/my_donations' => 'donations#my_donations'
  get '/donations/quality_check' => 'donations#quality_check'
  get '/donations/:id/quality_screen' => 'donations#quality_screen', as: :quality_screen
  resources :donations
  resources :categories
  resources :items
  get 'requests/next_status' => 'requests#next_status'
  get '/requests/my_requests' => 'requests#my_requests'
  get '/requests/popup' => 'requests#popup'
  get '/requests/volunteer' => 'requests#volunteer'
  get '/requests/:id/settle' => 'requests#settle', as: :settle_request
  get '/users/manage' => 'users#manage'
  resources :requests
  get 'public/index'
  devise_for :users, :path_prefix => 'my', controllers: { registrations: 'users/registrations', invitations: 'users/invitations' }
  resources :users
  get '/get-involved' => 'get_involved#index'
   
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#index"

end

app/models/request.rb
class Request < ApplicationRecord

  include FormattableAttributes

  URGENCIES = {
    '': 0,
    'Within 24 hours': 1,
    'Within 48 hours': 2,
    'Within a week': 3,
  }.freeze

  RELATIONSHIPS = {
    '': 0,
    'Foster Child': 1,
    'Juvenile Detention Center': 2,
    'Domestic Violence Center': 3,
    'Homeless Youth': 4,
    'Refugee/Displaced Person': 5,
  }.freeze

  COUNTIES = {
    '': 0,
    'Fulton': 1,
    'Dekalb': 2,
    'Gwinnett': 3,
    'Cobb': 4,
    'Clayton': 5,
    'Henry': 6,
    'Muscogee': 7,
    'Other (provide your address below)': 8
  }.freeze

  enum status: { pending: 0, claimed: 1, delivery_ready: 2 }
  # scope :pending,        -> { where(status: :pending) }
  # scope :claimed,        -> { where(status: :claimed) }
  # scope :delivery_ready, -> { where(status: :delivery_ready) }

  has_many :item_changes
  accepts_nested_attributes_for :item_changes, allow_destroy: true

  def any_blank(att)
    att.any? { |k, v| v.blank? }
  end

  validates_presence_of :relationship, :full_name, :urgency, :email, :availability,
                        :county, :meet, :phone, :item_changes

  validates_numericality_of :urgency, :relationship, :county, greater_than: 0, :message => "can't be blank"
  
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  
  validates :phone, phone: true

  validates :address,
            presence: true,
            length: { in: 7..200 },
            if: Proc.new { |a| a.meet == 2}

  validates :full_name,
            length: { in: 2..80 }

  # Returns how much time is left before the request is "past due," i.e. the
  # set urgency window has passed
  def due_time
    offset = 1.day
    case urgency
      when URGENCIES.fetch(:"Within 24 hours"); offset = 1.day
      when URGENCIES.fetch(:"Within 48 hours"); offset = 2.days
      when URGENCIES.fetch(:"Within a week"); offset = 1.week
    end

    created_at + offset
  end

  # Returns a hash which stores the inventory items that match each element inside request.item_changes to the actual inventory quantity.
  # If the item is either out of stock or in limited stock it will show up in this hash, otherwise it will not.
  # So, an item that has enough stock to fulfill the order will not be in the hash, otherwise it will have the form:
  # [itemChangeID: inventoryStock]. If someone requested 15 Boy's Size 6 Shoe's with ID 2 and there were only 5 in stock it would show 
  # [2: 5], where 2 is the ID of the 15 Boy's Size 6 in item_change and 5 is the actual stock in the "items" table
  def getItemStock
    itemsToStock = {}
    for item in item_changes
      # match item for inventory 
      matchingItems = Item.where(:itemType => item.itemType, :size => item.size, :category_id => item.category_id)

      # loop through and calculate the total inventory size
      inventoryQuantity = 0
      for matchedItem in matchingItems
        inventoryQuantity += matchedItem.quantity
      end 

      # this indicates there is not enough stock, so store the inventory quantity 
      if inventoryQuantity < item.quantity
        itemsToStock[item.id] = inventoryQuantity
      end 
    end 

    return itemsToStock
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy settle ]

  before_action :authenticate_user!, only: %i[ index, my_requests ]

  before_action -> { require_role(:root, :admin) }, only: :index

  before_action :check_timeout, only: :show

  # GET /requests or /requests.json
  def index
    @requests = Request.all
    @allCategories = Category.all
    @allItems = Item.all
  end

  # GET /requests/1 or /requests/1.json
  def show
    @allCategories = Category.all
    @allItems = Item.all
    @itemsToStock = @request.getItemStock()

  end

  def volunteer
  end

  def settle
    @show_settled = true
  end

  def next_status
    @request = Request.find(params[:format])
    @request.status = @request.status == "pending" ? "delivery_ready" : "claimed"
    
    if @request.status == "claimed"
      # iterate through items table and update quantity 
      for item in @request.item_changes
        # match item for inventory 
        matchingItems = Item.where(:itemType => item.itemType, :size => item.size, :category_id => item.category_id)
        quantityFulfilled = item.settle

        # contiously remove from each item until the set quantity has been removed 
        for matchedItem in matchingItems
          if matchedItem.quantity >= quantityFulfilled
            # perform the update quantity 
            # ex: quantityFulfilled = 20, and amount in inventory = 15, then quantityFulfilled becomes 5 and amount in inventory should become 0
            # it will then continue to loop to see if there are any more items it can remove
            amountToRemove = quantityFulfilled
            quantityFulfilled -= matchedItem.quantity
            matchedItem.quantity -= amountToRemove 
            matchedItem.save 
          end 
        end 
      end
    end 
    @request.save 

    redirect_to settle_request_path(@request)
  end

  # GET /requests/new
  def new
    @request = Request.new
    @allCategories = Category.all
    @allItems = Item.all
    1.times { @request.item_changes.build }
  end

  # GET /requests/1/edit
  def edit
    @allCategories = Category.all
    @allItems = Item.all
  end

  # GET /requests/my-requests
  def my_requests
    @allCategories = Category.all
    @allItems = Item.all
    @requests = current_user != nil ? Request.where("email like ?", "%#{current_user.email}%") : nil  
  end

  # GET /requests/popup
  def popup
    @request = Request.new
    default = ItemChange.create!(category: Category.all.sample, quantity: 1, itemType: 2, change_type: 2, size: Item.all.pluck(:size).uniq.sample)
    @request.item_changes << default
  end

  # POST /requests or /requests.json
  def create

    @allCategories = Category.all
    @allItems = Item.all
    @request = nil
    if request_params[:popup] == 'true'
      @request = Request.new(request_params.except(:item_changes_attributes, :popup))
    else
      @request = Request.new(request_params.except(:popup))
    end

    if request_params[:popup] == 'true'
      @request.full_name = "POPUP SHOP"
      @request.meet = 1
      @request.relationship = 1
      @request.email = 'carries.closets@gmail.com'
      @request.urgency = Request::URGENCIES[:'Within 24 hours']
      @request.availability = 'POPUP'
      @request.county = Request::COUNTIES[:Fulton]
      @request.phone = 678_555_5555

      items = request_params[:item_changes_attributes].values
      items = items.map{ |item| item.except(:_destroy, :id) } # Remove excess attribute
      @request.item_changes = ItemChange.create!(items)
    end


    respond_to do |format|

      if @request.save
        if request_params[:popup] != 'true'
          # ActionMailer should send email immediately after new request creation is saved
          UserMailer.with(request: @request).new_email.deliver_later # to DONEE who submitted request

          #if @request.urgency == 1 // new email settings will take care of this
          UserMailer.with(request: @request).new_admin_urgent_email.deliver_later # to ADMIN if URGENT
          # end

          UserMailer.with(request: @request).volunteer_email.deliver_later

        end


        format.html { redirect_to @request, notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else

        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    @allCategories = Category.all
    @allItems = Item.all

    respond_to do |format|

      if @request.update(request_params.except(:send_to_settle))
        @request.save

        if request_params[:send_to_settle] && current_user&.volunteer?
          format.html { redirect_to settle_request_path(@request), notice: "Request was successfully updated." }
        else
          format.html { redirect_to @request, notice: "Request was successfully updated." }
          format.json { render :show, status: :ok, location: @request }
        end

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @allCategories = Category.all
    @allItems = Item.all
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_request
    @request = Request.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def request_params
    params.require(:request).permit(:popup, :urgency, :full_name, :email, :phone, :relationship, :county, :meet, :address,
                                    :availability, :comments, :send_to_settle,
                                    item_changes_attributes: [:id, :category_id, :quantity, :settle, :itemType, :size,
                                                              :change_type, :_destroy])
  end

  def request_changes
    request_params.require(:item_changes_attributes)
  end

  # Redirects to :root if accessed by non-volunteer after 30 minutes to
  # protect information contained in request.
  def check_timeout
    require_role(:root, :volunteer) if @request.nil? || (Time.current.utc - @request.created_at.utc) / 1.minute > 30

  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_with(model: request, html: { class: 'pure-form pure-form-stacked' }) do |form| %>

  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="margins-needed">

  <div class="field">
    <%= form.label :urgency, 'How urgently do you need these items?' %>
    <%= form.select :urgency, Request::URGENCIES %>
  </div>

  <div class="field">
    <%= form.label :full_name, 'Full Name' %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone, 'Phone Number' %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :relationship, 'I am a guardian/foster parent/case manager for a...' %>
    <%= form.select :relationship, Request::RELATIONSHIPS %>
  </div>

  <div class="field">
    <%= form.label :county, 'Select county' %>
    <%= form.select :county, Request::COUNTIES %>
  </div>

  <div class="field">
    <label>
      <%= form.label :meet, 'Can you meet us at your local DFCS office?' %>
      <p>Don't know where your local DFCS office is? <%= link_to 'Find your county\'s DFCS location here.', 'https://dfcs.georgia.gov/locations', target: :_blank %></p>
    </label>
    <%= form.collection_radio_buttons :meet, [['Yes', 1], ['No, my address is:', 2]], :last, :first %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :availability, 'What\'s your availability?' %>
    <i>Please indicate your availability between 10 AM and 7 PM, Monday through Friday.</i>
    <%= form.text_field :availability %>
  </div>

  <%= render partial: 'form_helpers/item_selection', locals: { form: form, parent_f: :request } %>


  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/requests/_item_change_form.html.erb
<%= form_with(model: request, html: { class: 'pure-form pure-form-stacked' }) do |form| %>

  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="margins-needed">
    <% send_to_settle ||= false %>
    <% send_to_screen ||= false %>
    <%= render partial: 'form_helpers/item_selection', locals: { form: form, parent_f: :request, send_to_settle: send_to_settle, send_to_screen: send_to_screen } %>

    <div class="actions">
      <%= form.hidden_field :send_to_settle, value: send_to_settle %>
      <%= form.hidden_field :send_to_screen, value: send_to_screen %>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/requests/_item_selection.html.erb
<div class="field">
  <%= form.label :items, 'What items would you like to request?' %>
  <table>
    <thead>
    <tr>
      <th>Quantity</th>
      <th>Category</th>
      <th>Item Type</th>
      <th>Size</th>
    </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= form.number_field :items_quantity %></td>
        <td><%= form.select :items_category, Category.all.map { |category| category.name } %></td>
        <td><%= form.select :items_sizes, Item.all.map{ |item| item.size } %></td>
        <td><%= form.select :items_itemType, Item.all.map{ |item| item.itemType } %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/requests/_volunteer_request_block.html.erb
<div class="volunteer-request-list-block">
  <% isRequestElseDonation = request.respond_to?(:getItemStock) %>

  <% @itemsToStock = request.getItemStock() if isRequestElseDonation %>
  <ul>
    <% request.item_changes.limit(5).each do |item| %>
      <li>
        <%= item.description %>
        <% if !@itemsToStock.nil? && @itemsToStock.keys.any?(item.id) %>
          <% if @itemsToStock[item.id] > 0 %>
            - Limited Stock (<%= @itemsToStock[item.id] =%>)
          <% else %>
            - Out of Stock
          <% end %>
        <% end %>
      
      </li>
      
    <% end %>

    <% if request.item_changes.count > 5 %>
      <li><i><%= request.item_changes.count - 5 %> more items</i></li>
    <% end %>
  </ul>

  <% if isRequestElseDonation %>
    <b><i>Due in <%= time_ago_in_words(request.due_time) %></i></b>

    <p><%= link_to 'View', settle_request_path(request) %></p>
  <% else %>
    <p><%= link_to 'View', quality_screen_path(request) %></p>
  <% end %>
</div>

app/views/requests/edit.html.erb
<div class="container">
  <h1>Editing Request</h1>

  <%= render 'form', request: @request %>

  <%= link_to 'Show', @request %> |
  <%= link_to 'Back', :back %>
</div>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Urgency</th>
      <th>Full name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Relationship</th>
      <th>County</th>
      <th>Meet at DFCS</th>
      <th>Address</th>
      <th>Availability</th>
      <th>Items</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>

        <td><%= Request::URGENCIES.key(request.urgency) %></td>
        <td><%= request.full_name %></td>
        <td><%= request.email %></td>
        <td><%= request.phone %></td>
        <td><%= Request::RELATIONSHIPS.key(request.relationship) %></td>
        <td><%= Request::COUNTIES.key(request.county) %></td>

        <td><%= request.meet %></td>
        <td><%= request.address %></td>
        <td><%= request.availability %></td>
        <td>
            <% request.item_changes.limit(5).each do |item_change| %>
              <li><%= item_change.category.name %> <%= item_change.itemType %> (Size <%= item_change.size %>) x <%= item_change.quantity %></li>
            <% end %>
        </td>
        <td><%= request.comments %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>

        <td><%= button_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' }, class: "button-looks-like-link" %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/my_requests.html.erb
<h1>My Donation Requests</h1>

<table>
  <thead>
    <tr>
      <th>Urgency</th>
      <th>Full name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Relationship</th>
      <th>County</th>
      <th>Meet</th>
      <th>Address</th>
      <th>Availability</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% if @requests != nil %>
    <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.urgency %></td>
        <td><%= request.full_name %></td>
        <td><%= request.email %></td>
        <td><%= request.phone %></td>
        <td><%= request.relationship %></td>
        <td><%= request.county %></td>
        <td><%= request.meet %></td>
        <td><%= request.address %></td>
        <td><%= request.availability %></td>
        <td><%= request.comments %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>

        <td><%= button_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' }, class: "button-looks-like-link" %></td>

      </tr>
    <% end %>
    </tbody>
  <% end %>
</table>

<br>

<div class="links">
  <%= link_to 'New Request', new_request_path %>
</div>

app/views/requests/new.html.erb
<div class="container">
  <h1>New Request</h1>

  <%= render 'form', request: @request %>

  <%= link_to 'Back', :back %>
</div>

app/views/requests/popup.html.erb
<h1>New Pop-Up Shop Transaction</h1>
<%= form_with(model: @request, html: { class: 'pure-form pure-form-stacked' }) do |form| %>
  <%= form.hidden_field :popup, value: true %>
  <%= render partial: 'form_helpers/item_selection', locals: { form: form, parent_f: :donation } %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/settle.html.erb
<div class="margins-needed">
  <h1>Request a Donation: Summary</h1>
  <h2>Please review and confirm the summary of your request:</h2>

  <p>
    <strong>Urgency:</strong>
    <%= Request::URGENCIES.key(@request.urgency) %>
  </p>

  <p>
    <strong>Full name:</strong>
    <%= @request.full_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @request.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @request.phone %>
  </p>

  <% if @request.meet %>
    <p>
      <strong>County:</strong>
      <%= Request::COUNTIES.key(@request.county) %>

    </p>
  <% else %>
    <p>
      <strong>Address:</strong>
      <%= @request.address %>
    </p>
  <% end %>

  <p>
    <strong>Availability:</strong>
    <%= @request.availability %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= @request.comments %>
  </p>

  <% if current_user&.volunteer? %>
    <strong>Order Status:</strong>
    <%= @request.status.titleize %>
    <br>
  <% end %>

  <p>
    <strong>Requested Items:</strong>
    <% if current_user&.volunteer? %>
      <%= render partial: "item_change_form", locals: { request: @request, send_to_settle: current_user&.volunteer? } %>
    <% else %>
      <%@request.item_changes.each do |item|%>
        <p><%= item.description %>
      <%end%>
    <% end %>
  </p>

  <h1>Contact the donee!</h1>
  <i>Remember to contact the donee before you go to let them know when to meet and make sure they're still available.</i>
  <p>
    <strong>Full name:</strong>
    <%= @request.full_name %>
  </p>
  
  <p>
    <strong>Email:</strong>
    <%= @request.email %>
  </p>
  
  <p>
    <strong>Phone:</strong>
    <%= @request.phone %>
  </p>
  
  <% if @request.meet %>
    <p>
      <strong>County:</strong>
      <%= Request::COUNTIES.key(@request.county) %>
  
    </p>
  <% else %>
    <p>
      <strong>Address:</strong>
      <%= @request.address %>
    </p>
  <% end %>
  
  <p>
    <strong>Availability:</strong>
    <%= @request.availability %>
  </p>

  <% if current_user&.volunteer? && @request.status == "delivery_ready" %>
    <%= link_to "Mark Order Complete", requests_next_status_path(@request), class: "home-link" %>
    <br>
  <% end %>

  <% if current_user&.volunteer? && @request.status == "pending" %>
    <%= link_to "Mark Ready for Delivery", requests_next_status_path(@request), class: "home-link" %>
    <br>
  <% end %>

  <%= link_to 'Edit', edit_request_path(@request) %> |
  <%= link_to 'Back', :back %>
</div>

app/views/requests/show.html.erb
<div class="container">
<div class="margins-needed">
<h1>Request a Donation: Summary</h1>
<h2>Please review and confirm the summary of your request:</h2>

<p>
  <strong>Urgency:</strong>
  <%= Request::URGENCIES.key(@request.urgency) %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @request.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @request.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @request.phone %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= Request::RELATIONSHIPS.key(@request.relationship) %>
</p>


<% if @request.meet %>
  <p>
    <strong>County:</strong>
    <%= Request::COUNTIES.key(@request.county) %>

  </p>
<% else %>
  <p>
    <strong>Address:</strong>
    <%= @request.address %>
  </p>
<% end %>

<p>
  <strong>Availability:</strong>
  <%= @request.availability %>
</p>

<p>
  <strong>Requested Items:</strong>
  <% @request.item_changes.each do |item|%>
    <p><%= item.quantity %> <%= Category.find(item.category_id).name %> <%= item.itemType %>, size: <%= item.size %></p>
  <%end%>
  
</p>

<p>
  <strong>Comments:</strong>
  <%= @request.comments %>
</p>

<% if current_user&.volunteer? %>
  <strong>Order Status:</strong>
  <%= @request.status.titleize %>
  <br>
<% end %>

<% if current_user&.volunteer? && @request.status == "pending" %>
  <%= link_to "Mark Ready for Delivery", requests_next_status_path(@request), class: "home-link" %>
  <br>
<% end %>
<% if current_user&.volunteer? %>
  <h1>Contact the donee!</h1>
  <i>Remember to contact the donee before you go to let them know when to meet and make sure they're still available.</i>
  <p>
    <strong>Full name:</strong>
    <%= @request.full_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @request.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @request.phone %>
  </p>

  <% if @request.meet %>
    <p>
      <strong>County:</strong>
      <%= Request::COUNTIES.key(@request.county) %>

    </p>
  <% else %>
    <p>
      <strong>Address:</strong>
      <%= @request.address %>
    </p>
  <% end %>

  <p>
    <strong>Availability:</strong>
    <%= @request.availability %>
  </p>

  <% if current_user&.volunteer? && @request.status == "delivery_ready" %>
    <%= link_to "Mark Order Complete", requests_next_status_path(@request), class: "home-link" %>
    <br>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', :back %>
</div>
</div>

app/views/requests/volunteer.html.erb
<h1>Pending Requests (<%= Request.pending.count %>)</h1>
<% Request.pending.each do |pending_request| %>
  <%= render partial: 'volunteer_request_block', locals: { request: pending_request } %>
<% end %>

<h1>Ready to Deliver (<%= Request.delivery_ready.count %>)</h1>
<% Request.delivery_ready.each do |delivery_ready| %>
  <%= render partial: 'volunteer_request_block', locals: { request: delivery_ready } %>
<% end %>