config/routes.rb
Rails.application.routes.draw do


  resources :email_settings
  get '/donations/my_donations' => 'donations#my_donations'
  get '/donations/quality_check' => 'donations#quality_check'
  get '/donations/:id/quality_screen' => 'donations#quality_screen', as: :quality_screen
  resources :donations
  resources :categories
  resources :items
  get 'requests/next_status' => 'requests#next_status'
  get '/requests/my_requests' => 'requests#my_requests'
  get '/requests/popup' => 'requests#popup'
  get '/requests/volunteer' => 'requests#volunteer'
  get '/requests/:id/settle' => 'requests#settle', as: :settle_request
  get '/users/manage' => 'users#manage'
  resources :requests
  get 'public/index'
  devise_for :users, :path_prefix => 'my', controllers: { registrations: 'users/registrations', invitations: 'users/invitations' }
  resources :users
  get '/get-involved' => 'get_involved#index'
   
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#index"

end

app/models/donation.rb
class Donation < ApplicationRecord

  include FormattableAttributes

  has_many :item_changes
  accepts_nested_attributes_for :item_changes, allow_destroy: true
  
  validates_presence_of :full_name, :email, :availability,
                        :county, :meet, :phone, :item_changes

#   COUNTIES = {
#     '': 0,
#     'Fulton': 1,
#     'Dekalb': 2,
#     'Gwinnett': 3,
#     'Cobb': 4,
#     'Clayton': 5,
#     'Henry': 6,
#     'Muscogee': 7,
#     'Other (provide your address below)': 8
#   }.freeze
  
#   validates_presence_of :full_name, :email, :availability,
#                         :county, :meet, :phone, :items


  validates_numericality_of :county, greater_than: 0, :message => "can't be blank"
  
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  
  validates :phone, phone: true

  validates :address,
            presence: true,
            length: { in: 7..200 },
            if: Proc.new { |a| a.meet == 2}

  validates :full_name,
            length: { in: 2..80 }


  
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  before_action :set_categories_and_items
  before_action :set_donation, only: %i[ show edit update destroy quality_screen ]

  
  before_action :authenticate_user!, only: %i[ index, my_donations ]

  before_action -> { require_role(:root, :admin) }, only: :index

  before_action -> { require_role(:root, :volunteer) }, only: :quality_screen


  # GET /donations or /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1 or /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new

    1.times { @donation.item_changes.build }

  end

  # GET /donations/1/edit
  def edit
  end


  def quality_check
  end

  def quality_screen

  end

  # GET /donations/my-donations
  def my_donations
    @donations = current_user != nil ? Donation.where("email like ?", "%#{current_user.email}%") : nil  
  end 

  # POST /donations or /donations.json
  def create

    @donation = Donation.new(donation_params)
  

    respond_to do |format|
      if @donation.save

        UserMailer.with(donation: @donation).new_donor_email.deliver_later

        format.html { redirect_to @donation, notice: "Donation was successfully created." }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1 or /donations/1.json
  def update
    respond_to do |format|

      if @donation.update(donation_params.except(:send_to_settle, :send_to_screen))
        @donation.save

        if donation_params[:send_to_screen] && current_user&.volunteer?
          format.html { redirect_to quality_screen_path(@donation), notice: "Donation was successfully updated." }
        else
          format.html { redirect_to @donation, notice: "Donation was successfully updated." }
          format.json { render :show, status: :ok, location: @donation }
        end

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1 or /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: "Donation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donation_params

      params.require(:donation).permit(:full_name, :email, :phone, :county, :meet, :address, :availability, :comments,
                                       :send_to_settle, :send_to_screen,
                                       item_changes_attributes: [:id, :category_id, :quantity, :itemType, :size,
                                                                 :change_type, :settle, :_destroy])
    end

  def set_categories_and_items
    @allCategories = Category.all
    @allItems = Item.all
  end

end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_with(model: donation) do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
        <% donation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="margins-needed">
  <div class="field">
    <%= form.label :full_name, 'Full Name' %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :county, 'Select county' %>
    <%= form.select :county, Request::COUNTIES %>
  </div>

  <div class="field">
    <label>
      <%= form.label :meet, 'Can you meet us at your local DFCS office?' %>
      <p>Don't know where your local DFCS office is? <%= link_to 'Find your county\'s DFCS location here.', 'https://dfcs.georgia.gov/locations', target: :_blank %></p>
    </label>
    <%= form.collection_radio_buttons :meet, [['Yes', 1], ['No, my address is:', 2]], :last, :first %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :availability, 'What\'s your availability?' %>
    <i>Please indicate your availability between 10 AM and 7 PM, Monday through Friday.</i>
    <br />
    <%= form.text_field :availability %>
  </div>


  <%= render partial: 'form_helpers/item_selection', locals: { form: form, parent_f: :donation } %> 


  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donations</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>County</th>
      <th>Meet at DFCS</th>
      <th>Address</th>
      <th>Availability</th>
      <th>Items</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.full_name %></td>
        <td><%= donation.email %></td>
        <td><%= donation.phone %></td>
        <td><%= Request::COUNTIES.key(donation.county) %></td>
        <td><%= donation.meet %></td>
        <td><%= donation.address %></td>
        <td><%= donation.availability %></td>
        <td>
          <% donation.item_changes.limit(5).each do |item_change| %>
            <li><%= item_change.description %></li>
          <% end %>
        </td>
        <td><%= donation.comments %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= button_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' }, class: "button-looks-like-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="links">
  <%= link_to 'New Donation', new_donation_path %>
</div>

app/views/donations/my_donations.html.erb
<p id="notice"><%= notice %></p>

<h1>My Donations</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>County</th>
      <th>Meet at DFCS</th>
      <th>Address</th>
      <th>Availability</th>
      <th>Items</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.full_name %></td>
        <td><%= donation.email %></td>
        <td><%= donation.phone %></td>
        <td><%= Request::COUNTIES.key(donation.county) %></td>
        <td><%= donation.meet %></td>
        <td><%= donation.address %></td>
        <td><%= donation.availability %></td>

        <td>ITEMS HERE</td>

        <td><%= donation.comments %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= button_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' }, class: "button-looks-like-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<div class="container">
  <h1>New Donation</h1>

  <%= render 'form', donation: @donation %>

  <%= link_to 'Back', donations_path %>
</div>

app/views/donations/quality_check.html.erb
<p id="notice"><%= notice %></p>

<h1>Donation Quality (<%= Donation.all.count %>)</h1>
<% Donation.all.each do |donation| %>
  <%= render partial: 'requests/volunteer_request_block', locals: { request: donation } %>
<% end %>

app/views/donations/quality_screen.html.erb
<div class="margins-needed">
  <h1>Quality Donation Screening</h1>
  <p>Remember to wear gloves and a mask while processing donations!</p>
  <p>Please sort the items to make sure we only accept items that meet Carrie's Closet's quality standards, based on the CUTE acronym:</p>
  <div class="centered-div">
    <ul class="cute">
      <li class="cute">Clean</li>
      <li class="cute">Usable</li>
      <li class="cute">Timely</li>
      <li class="cute">Equipment</li>
    </ul>
  </div>
  <p>If an item is equipment, such as a stroller, remember that it must be stored differently in inventory.</p>
  <p>Adjust the quantities below to only show the items that Carrie's Closet will accept, <i>not</i> anything that will be thrown out.</p>

  <% if current_user&.volunteer? %>
    <%= render partial: "requests/item_change_form", locals: { request: @donation, send_to_screen: current_user&.volunteer? } %>
  <% else %>
    <% @donation.item_changes.each do |item| %>
      <p><%= item.description %>
    <% end %>
  <% end %>

  <h1>Contact the donor!</h1>
  <i>Remember to contact the donor before you go to let them know when to meet and make sure they're still available.</i>
  <p>
    <strong>Full name:</strong>
    <%= @donation.full_name %>
  </p>
  
  <p>
    <strong>Email:</strong>
    <%= @donation.email %>
  </p>
  
  <p>
    <strong>Phone:</strong>
    <%= @donation.phone %>
  </p>
  
  <% if @donation.meet %>
    <p>
      <strong>County:</strong>
      <%= Request::COUNTIES.key(@donation.county) %>
  
    </p>
  <% else %>
    <p>
      <strong>Address:</strong>
      <%= @donation.address %>
    </p>
  <% end %>
  
  <p>
    <strong>Availability:</strong>
    <%= @donation.availability %>
  </p>

  <%= link_to 'Edit', edit_donation_path(@donation) %> |
  <%= link_to 'Back', :back %>
</div>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @donation.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @donation.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @donation.phone %>
</p>

<% if @donation.meet %>
  <p>
    <strong>County:</strong>
    <%= Request::COUNTIES.key(@donation.county) %>
  </p>
<% else %>
  <p>
    <strong>Address:</strong>
    <%= @donation.address %>
  </p>
<% end %>

<p>
  <strong>Availability:</strong>
  <%= @donation.availability %>
</p>

<p>
  <strong>Items:</strong>

  <%@donation.item_changes.each do |item|%>
     <p><%= item.quantity %> <%= Category.find(item.category_id).name %> <%= item.itemType %>, size: <%= item.size %></p>
  <%end%>

</p>

<p>
  <strong>Comments:</strong>
  <%= @donation.comments %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>