config/routes.rb
Rails.application.routes.draw do


  resources :email_settings
  get '/donations/my_donations' => 'donations#my_donations'
  get '/donations/quality_check' => 'donations#quality_check'
  get '/donations/:id/quality_screen' => 'donations#quality_screen', as: :quality_screen
  resources :donations
  resources :categories
  resources :items
  get 'requests/next_status' => 'requests#next_status'
  get '/requests/my_requests' => 'requests#my_requests'
  get '/requests/popup' => 'requests#popup'
  get '/requests/volunteer' => 'requests#volunteer'
  get '/requests/:id/settle' => 'requests#settle', as: :settle_request
  get '/users/manage' => 'users#manage'
  resources :requests
  get 'public/index'
  devise_for :users, :path_prefix => 'my', controllers: { registrations: 'users/registrations', invitations: 'users/invitations' }
  resources :users
  get '/get-involved' => 'get_involved#index'
   
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#index"

end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :quantity, :itemType, :size

  belongs_to :category


  validates_numericality_of :quantity, greater_than: -1, :message => "can't be negative"

  def category
    Category.find(category_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action -> { require_role(:root, :admin) }, only: %i[ show edit update destroy index ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    Category.where(id: item_params["category_id"]).each do |category|
      item_params["size"].split(",").each do |size|
        puts "Creating #{item_params["itemType"]} with category #{category.name} with size #{size}"
        @item = Item.new(quantity: 0,
                         itemType: item_params["itemType"],
                         size: size,
                         category_id: category.id)
        puts @item, @item.save!
      end
    end

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully created." }
      format.json { render :show, status: :created, location: @item }
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(size: item_params["size"], itemType: item_params["itemType"], quantity: item_params["quantity"])
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:quantity, :itemType, :size, :category_id => [])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :itemType, "Name" %><br/>
    <%= form.text_field :itemType %>
  </div>

  <% if !item.id.nil? %>
    <div class="field">
      <%= form.label :quantity %>
      <%= form.number_field :quantity %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <br>
    <% if item.id.nil? %>
      <%= collection_check_boxes(:item, :category_id, Category.all, :id, :name) %>
    <% else %>
      <li><%= item.category.name %></li>
      <%= form.hidden_field :category %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :size, "Size Options" %>
    <i>Ex: S, M, L</i>
    <br />
    <%= form.text_field :size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <h1>Editing Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Category</th>
      <th>Name</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.quantity %></td>
        <td><%= item.category.name %></td>
        <td><%= item.itemType %></td>
        <td><%= item.size %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= button_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "button-looks-like-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
  <div class = "centered-div">
    <%= link_to 'Add Item Type', new_item_path, class: "home-link" %>
  </div>
<br />
  <div class = "centered-div">
    <%= link_to "View Pending Donations", "donations/", class: "home-link" %>
  </div>
<br />

app/views/items/new.html.erb
<div class="container">
  <h1>New Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.itemType %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Size:</strong>
  <%= @item.size %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>
<div class = "centered-div">
  <%= link_to "View Inventory", "/items", class: "home-link" %>
</div>