config/routes.rb
Rails.application.routes.draw do


  resources :email_settings
  get '/donations/my_donations' => 'donations#my_donations'
  get '/donations/quality_check' => 'donations#quality_check'
  get '/donations/:id/quality_screen' => 'donations#quality_screen', as: :quality_screen
  resources :donations
  resources :categories
  resources :items
  get 'requests/next_status' => 'requests#next_status'
  get '/requests/my_requests' => 'requests#my_requests'
  get '/requests/popup' => 'requests#popup'
  get '/requests/volunteer' => 'requests#volunteer'
  get '/requests/:id/settle' => 'requests#settle', as: :settle_request
  get '/users/manage' => 'users#manage'
  resources :requests
  get 'public/index'
  devise_for :users, :path_prefix => 'my', controllers: { registrations: 'users/registrations', invitations: 'users/invitations' }
  resources :users
  get '/get-involved' => 'get_involved#index'
   
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#index"

end

app/models/category.rb
class Category < ApplicationRecord

    has_many :items

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <h1>Editing Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Show', @category %> |
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Categories</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="links">
    <%= link_to 'New Category', new_category_path %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h1>New Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>